name: Create 404 page, update base href, and deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - gh_pages

jobs:
  create-404-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: 'index.html'
          base_href: '/tabito.release/'

      - name: Create 404 page
        run: |
          cp index.html 404.html
          echo "404 page created."

      - name: Add script section to files
        run: |
          sed -i 's+</head>+<script src="resources/redirect.js"></script>\n</head>+' 404.html
          sed -i 's+</head>+<script src="resources/redirect.js"></script>\n</head>+' index.html          
          echo "Script section added to files."

      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          echo ".nojekyll file created."

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add index.html 404.html .nojekyll
          git commit -m "Update base href, create 404 page, add script section and .nojekyll file"
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
