name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on pushes to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: 'index.html'
          base_href: '/tabito.release/'

      - name: Create 404 page
        run: |
          cp index.html 404.html
          echo "404 page created."

      - name: Add script section to files
        run: |
          sed -i 's+</head>+<script src="resources/redirect.js"></script>\n</head>+' 404.html
          sed -i 's+</head>+<script src="resources/redirect.js"></script>\n</head>+' index.html          
          echo "Script section added to files."

      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          echo ".nojekyll file created."

      - name: Commit changes
        run: |
          git add index.html 404.html .nojekyll
          git commit -m "Update base href, create 404 page, add script section and .nojekyll file"

      - name: Debug Output
        run: |
          git status
          git branch -a
          git log --oneline -n 10

      - name: Push changes to GitHub
        run: git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
